version: "3.9"
services:
  architecture:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    command: uvicorn src.app:api --host 0.0.0.0 --port 80 --reload
    ports:
      - "5005:80"

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"